"""initial migrate

Revision ID: d2dd6acd9e1a
Revises: 
Create Date: 2022-04-04 15:42:00.484526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2dd6acd9e1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.alter_column('projects', 'created_at',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'project_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'tags',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'tools',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'project_link',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('ix_projects_id', table_name='projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.alter_column('projects', 'project_link',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'tools',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'tags',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'project_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
